# Generated by Django 3.2.4 on 2021-06-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.league')),
            ],
        ),
    ]
