# Generated by Django 3.2.4 on 2021-06-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=3)),
                ('position', models.CharField(max_length=5)),
                ('yearborn', models.IntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='scout.team')),
            ],
        ),
    ]
