# Generated by Django 3.2.4 on 2021-06-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='squad',
            new_name='team',
        ),
    ]
