# Generated by Django 3.2.4 on 2021-06-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_rename_squad_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingTime',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('matchesplayed', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('minutesper90', models.FloatField()),
            ],
        ),
    ]
