# Generated by Django 3.2.4 on 2021-06-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0006_generalstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedGeneralStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('expectedgoals', models.FloatField()),
                ('nonPKexpectedgoals', models.FloatField()),
                ('expectedassists', models.FloatField()),
                ('exnonPKgoalsandassists', models.FloatField()),
            ],
        ),
    ]
