# Generated by Django 3.2.4 on 2021-06-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0008_datastorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedGeneralStatsPer90',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('exgoals', models.FloatField()),
                ('exassists', models.FloatField()),
                ('exgoalsplusassists', models.FloatField()),
                ('exnonPKgoals', models.FloatField()),
                ('exnonPKgoalsplusassists', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStatsPer90',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('goals', models.FloatField()),
                ('assists', models.FloatField()),
                ('goalsplusassists', models.FloatField()),
                ('nonPKgoals', models.FloatField()),
                ('nonPKgoalsplusassists', models.FloatField()),
            ],
        ),
    ]
