# Generated by Django 3.2.4 on 2021-06-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0009_expectedgeneralstatsper90_generalstatsper90'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerialDuels',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('percentagewon', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataStorage',
        ),
        migrations.RemoveField(
            model_name='expectedgeneralstatsper90',
            name='player',
        ),
        migrations.RemoveField(
            model_name='generalstatsper90',
            name='player',
        ),
        migrations.RenameField(
            model_name='generalstats',
            old_name='PKgoals',
            new_name='PKconceded',
        ),
        migrations.RenameField(
            model_name='generalstats',
            old_name='assists',
            new_name='PKwon',
        ),
        migrations.RenameField(
            model_name='generalstats',
            old_name='attemptedPK',
            new_name='ballsrecovered',
        ),
        migrations.RenameField(
            model_name='generalstats',
            old_name='goals',
            new_name='foulscommited',
        ),
        migrations.RenameField(
            model_name='generalstats',
            old_name='nonPKgoals',
            new_name='foulsdrawn',
        ),
        migrations.AddField(
            model_name='generalstats',
            name='offsides',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalstats',
            name='owngoals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalstats',
            name='twoyellows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExpectedGeneralStats',
        ),
        migrations.DeleteModel(
            name='ExpectedGeneralStatsPer90',
        ),
        migrations.DeleteModel(
            name='GeneralStatsPer90',
        ),
    ]
