# Generated by Django 3.2.4 on 2021-06-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0010_auto_20210618_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralStats',
            new_name='MiscStats',
        ),
    ]
