# Generated by Django 3.2.4 on 2021-06-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0011_rename_generalstats_miscstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootingStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('goals', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('shotsontarget', models.IntegerField()),
                ('pershotsontarget', models.FloatField()),
                ('shotsper90', models.FloatField()),
                ('shotsontargetper90', models.FloatField()),
                ('goalspershot', models.FloatField()),
                ('goalpershotontarget', models.FloatField()),
                ('avgdistance', models.FloatField()),
                ('freekick', models.IntegerField()),
                ('PKmade', models.IntegerField()),
                ('PKattempted', models.IntegerField()),
                ('exgoals', models.FloatField()),
                ('exnonPKgoals', models.FloatField()),
                ('nonPKexgoalspershot', models.FloatField()),
                ('goalsminusexgoals', models.FloatField()),
                ('nonpkgoalsminusexnonPKgoals', models.FloatField()),
            ],
        ),
    ]
