# Generated by Django 3.2.4 on 2021-06-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0012_shootingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossessionStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('touches', models.IntegerField()),
                ('defensivebox', models.IntegerField()),
                ('defensive3rd', models.IntegerField()),
                ('middle3rd', models.IntegerField()),
                ('attacking3rd', models.IntegerField()),
                ('attackingbox', models.IntegerField()),
                ('liveball', models.IntegerField()),
                ('sucessfuldribbles', models.IntegerField()),
                ('attempteddribbles', models.IntegerField()),
                ('dribblesucesspercentage', models.FloatField()),
                ('playerspassed', models.IntegerField()),
                ('carries', models.IntegerField()),
                ('totaldistance', models.IntegerField()),
                ('progressivedistance', models.IntegerField()),
                ('progressivecarries', models.IntegerField()),
                ('carrieslast3rd', models.IntegerField()),
                ('carriesattackingbox', models.IntegerField()),
                ('miscarries', models.IntegerField()),
                ('disarmed', models.IntegerField()),
                ('targeted', models.IntegerField()),
                ('recieved', models.IntegerField()),
                ('recievedsucesspercentage', models.FloatField()),
                ('progressivepassesrecieved', models.IntegerField()),
            ],
        ),
    ]
