# Generated by Django 3.2.4 on 2021-06-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0013_possessionstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassingStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('totalcomplete', models.IntegerField()),
                ('totalattempted', models.IntegerField()),
                ('totalcomppercentage', models.FloatField()),
                ('totaldistance', models.IntegerField()),
                ('progressivedistance', models.IntegerField()),
                ('shortcomplete', models.IntegerField()),
                ('shortattempted', models.IntegerField()),
                ('shortcompprecentage', models.FloatField()),
                ('mediumcomplete', models.IntegerField()),
                ('mediumattempted', models.IntegerField()),
                ('mediumcompprecentage', models.FloatField()),
                ('longcomplete', models.IntegerField()),
                ('longattempted', models.IntegerField()),
                ('longcompprecentage', models.FloatField()),
                ('assists', models.IntegerField()),
                ('exassists', models.FloatField()),
                ('assistsminusexassists', models.FloatField()),
                ('passledtoshot', models.IntegerField()),
                ('passesintofinal3rd', models.IntegerField()),
                ('passesattackingbox', models.IntegerField()),
                ('crossintobox', models.IntegerField()),
                ('progressivepasses', models.IntegerField()),
            ],
        ),
    ]
