# Generated by Django 3.2.4 on 2021-06-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0014_passingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTypesStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('totalattempts', models.IntegerField()),
                ('liveball', models.IntegerField()),
                ('deadball', models.IntegerField()),
                ('freekicks', models.IntegerField()),
                ('throughball', models.IntegerField()),
                ('underpressure', models.IntegerField()),
                ('plus40yards', models.IntegerField()),
                ('crosses', models.IntegerField()),
                ('cornerkicks', models.IntegerField()),
                ('CKinswing', models.IntegerField()),
                ('CKoutswing', models.IntegerField()),
                ('CKstraight', models.IntegerField()),
                ('groundpass', models.IntegerField()),
                ('lowpass', models.IntegerField()),
                ('highpass', models.IntegerField()),
                ('leftfootpass', models.IntegerField()),
                ('rightfootpass', models.IntegerField()),
                ('header', models.IntegerField()),
                ('throwin', models.IntegerField()),
                ('other', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('offside', models.IntegerField()),
                ('outofbounds', models.IntegerField()),
                ('intercepted', models.IntegerField()),
                ('blocks', models.IntegerField()),
            ],
        ),
    ]
