# Generated by Django 3.2.4 on 2021-06-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0015_passtypesstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passtypesstats',
            old_name='blocks',
            new_name='blocked',
        ),
    ]
