# Generated by Django 3.2.4 on 2021-06-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0016_rename_blocks_passtypesstats_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefensiveStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('tackles', models.IntegerField()),
                ('tackleswon', models.IntegerField()),
                ('tacklesdef3rd', models.IntegerField()),
                ('tacklesmid3rd', models.IntegerField()),
                ('tacklesatt3rd', models.IntegerField()),
                ('dribblerstackled', models.IntegerField()),
                ('totalattempts', models.IntegerField()),
                ('sucessvsdribble', models.FloatField()),
                ('beatbydribble', models.IntegerField()),
                ('totalpressure', models.IntegerField()),
                ('sucessfulpressure', models.IntegerField()),
                ('presssucessper', models.FloatField()),
                ('pressdef3rd', models.IntegerField()),
                ('pressmid3rd', models.IntegerField()),
                ('pressatt3rd', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('shotblocks', models.IntegerField()),
                ('shotontargetblocks', models.IntegerField()),
                ('passblocks', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('tacklesplusints', models.IntegerField()),
                ('clearings', models.IntegerField()),
                ('errors', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='possessionstats',
            old_name='attacking3rd',
            new_name='touchesatt3rd',
        ),
        migrations.RenameField(
            model_name='possessionstats',
            old_name='attackingbox',
            new_name='touchesattbox',
        ),
        migrations.RenameField(
            model_name='possessionstats',
            old_name='defensive3rd',
            new_name='touchesdef3rd',
        ),
        migrations.RenameField(
            model_name='possessionstats',
            old_name='defensivebox',
            new_name='touchesdefbox',
        ),
        migrations.RenameField(
            model_name='possessionstats',
            old_name='middle3rd',
            new_name='touchesmid3rd',
        ),
    ]
