# Generated by Django 3.2.4 on 2021-06-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0017_auto_20210624_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalShotCreationStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('shotcreatingactions', models.IntegerField()),
                ('shotcreatingactionsper90', models.FloatField()),
                ('SCAliveballpass', models.IntegerField()),
                ('SCAdeadballpass', models.IntegerField()),
                ('SCAdribble', models.IntegerField()),
                ('SCAshots', models.IntegerField()),
                ('SCAfoulsdrawn', models.IntegerField()),
                ('SCAdefensiveaction', models.IntegerField()),
                ('goalcreatingaction', models.IntegerField()),
                ('goalcreatingactionper90', models.FloatField()),
                ('GCAliveballpass', models.IntegerField()),
                ('GCAdeadballpass', models.IntegerField()),
                ('GCAdribble', models.IntegerField()),
                ('GCAshots', models.IntegerField()),
                ('GCAfoulsdrawn', models.IntegerField()),
                ('GCAdefensiveaction', models.IntegerField()),
            ],
        ),
    ]
