# Generated by Django 3.2.4 on 2021-06-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0018_goalshotcreationstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalkeepingStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('goalsallowed', models.IntegerField()),
                ('goalsallowedper90', models.FloatField()),
                ('shotsontargetagainst', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('savesper', models.FloatField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('cleansheets', models.IntegerField()),
                ('cleansheetsper', models.FloatField()),
                ('PKtotal', models.IntegerField()),
                ('PKallowed', models.IntegerField()),
                ('PKsaved', models.IntegerField()),
                ('PKmissed', models.IntegerField()),
                ('PKsaveper', models.FloatField()),
                ('FKgoals', models.IntegerField()),
                ('CKgoals', models.IntegerField()),
                ('OGgoals', models.IntegerField()),
                ('exgoalsallowed', models.FloatField()),
                ('exgoalsallowedminusgoalsallowed', models.FloatField()),
                ('exgoalsallowedminusgoalsallowedper90', models.FloatField()),
                ('passesover40yrdscompleted', models.IntegerField()),
                ('passesover40yrdsattempted', models.IntegerField()),
                ('passesover40yrdscmpper', models.FloatField()),
                ('passesattempted', models.IntegerField()),
                ('throwsattempted', models.IntegerField()),
                ('passlaunchper', models.FloatField()),
                ('passavglength', models.FloatField()),
                ('GKattempted', models.IntegerField()),
                ('GKlaunchper', models.FloatField()),
                ('GKavglength', models.FloatField()),
                ('attemptedcrosses', models.IntegerField()),
                ('crossesstoped', models.IntegerField()),
                ('crossstopper', models.FloatField()),
                ('DAOB', models.IntegerField()),
                ('DAOBper90', models.FloatField()),
                ('DAOBavgdistance', models.FloatField()),
            ],
        ),
    ]
