# Generated by Django 3.2.4 on 2021-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0019_goalkeepingstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalkeepingstats',
            name='exgoalsallowedperSoT',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
