# Generated by Django 3.2.4 on 2021-07-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0020_goalkeepingstats_exgoalsallowedpersot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStats',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scout.player')),
                ('weeklysalary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('yearlysalary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(max_length=20)),
                ('contractlength', models.IntegerField()),
                ('estimatedtotal', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Salary Stats',
            },
        ),
        migrations.AlterModelOptions(
            name='aerialduels',
            options={'verbose_name_plural': 'Aerial Duels'},
        ),
        migrations.AlterModelOptions(
            name='defensivestats',
            options={'verbose_name_plural': 'Defensive Stats'},
        ),
        migrations.AlterModelOptions(
            name='goalkeepingstats',
            options={'verbose_name_plural': 'Goalkeeping Stats'},
        ),
        migrations.AlterModelOptions(
            name='goalshotcreationstats',
            options={'verbose_name_plural': 'Goal and Shot Creation Stats'},
        ),
        migrations.AlterModelOptions(
            name='miscstats',
            options={'verbose_name_plural': 'Misc Stats'},
        ),
        migrations.AlterModelOptions(
            name='passingstats',
            options={'verbose_name_plural': 'Passing Stats'},
        ),
        migrations.AlterModelOptions(
            name='passtypesstats',
            options={'verbose_name_plural': 'Pass Type Stats'},
        ),
        migrations.AlterModelOptions(
            name='playingtime',
            options={'verbose_name_plural': 'Playing Time'},
        ),
        migrations.AlterModelOptions(
            name='possessionstats',
            options={'verbose_name_plural': 'Possession Stats'},
        ),
        migrations.AlterModelOptions(
            name='shootingstats',
            options={'verbose_name_plural': 'Shooting Stats'},
        ),
    ]
