# Generated by Django 3.2.4 on 2021-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0021_auto_20210704_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='posord',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
