# Generated by Django 3.2.4 on 2021-07-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0022_player_posord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salaries', serialize=False, to='scout.player'),
        ),
    ]
