# Generated by Django 3.2.4 on 2021-07-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0023_alter_salarystats_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerialduels',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aerial', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='defensivestats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='defensive', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='goalkeepingstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='goalkeeping', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='goalshotcreationstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gsc', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='miscstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='misc', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passing', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='passtypesstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passtypes', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='playingtime',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='playingtime', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='possessionstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='possession', serialize=False, to='scout.player'),
        ),
        migrations.AlterField(
            model_name='shootingstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shooting', serialize=False, to='scout.player'),
        ),
    ]
