# Generated by Django 3.2.4 on 2021-07-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0024_auto_20210705_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['posord']},
        ),
    ]
