# Generated by Django 3.2.4 on 2021-07-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0026_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['posord']},
        ),
    ]
