# Generated by Django 3.2.4 on 2021-07-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0027_alter_player_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teamstats', serialize=False, to='scout.team')),
                ('leagueranking', models.IntegerField()),
                ('matchesplayed', models.IntegerField()),
                ('matcheswon', models.IntegerField()),
                ('matchesdrawn', models.IntegerField()),
                ('matcheslost', models.IntegerField()),
                ('goalsfor', models.IntegerField()),
                ('goalsagainst', models.IntegerField()),
                ('goaldifference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('pointspergame', models.FloatField()),
                ('exgoals', models.FloatField()),
                ('exgoalsagainst', models.FloatField()),
                ('exgoaldifference', models.FloatField()),
                ('exgoaldifferenceper90', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'General Team Stats',
            },
        ),
    ]
